import { NextResponse } from "next/server"
import type Stripe from "stripe"

import { syncSubscriptionById } from "@/lib/billing-store"
import { getStripe, isBillingConfigured } from "@/lib/stripe"

/**
 * Where a paid plan actually gets granted.
 *
 * Fulfillment can't live on the checkout success page: a customer who pays and
 * then closes the tab never loads it, and a delayed payment method confirms
 * hours later. Stripe tells us here instead — and keeps telling us, which is
 * the only way renewals, failed payments and cancellations ever reach the
 * database.
 *
 * Point the Stripe CLI at it while developing:
 *   stripe listen --forward-to localhost:3000/api/webhooks/stripe
 */

/** The events that can change what a workspace is entitled to. */
const HANDLED_EVENTS = new Set<Stripe.Event["type"]>([
  // Checkout finished. With a delayed payment method it can arrive unpaid,
  // hence the `payment_status` gate below.
  "checkout.session.completed",
  "checkout.session.async_payment_succeeded",
  "checkout.session.async_payment_failed",
  // The subscription's own lifecycle: upgrades and downgrades from the portal,
  // cancellations, and trials ending.
  "customer.subscription.created",
  "customer.subscription.updated",
  "customer.subscription.deleted",
  // Renewals and dunning. `invoice.paid` is what restores a `past_due`
  // workspace once a retry finally goes through.
  "invoice.paid",
  "invoice.payment_failed",
])

function subscriptionIdFrom(
  value: string | Stripe.Subscription | null | undefined
) {
  if (!value) return null

  return typeof value === "string" ? value : value.id
}

export async function POST(request: Request) {
  if (!isBillingConfigured()) {
    return NextResponse.json({ error: "Billing is off." }, { status: 503 })
  }

  const secret = process.env.STRIPE_WEBHOOK_SECRET

  if (!secret) {
    console.error("[stripe] STRIPE_WEBHOOK_SECRET is not set")

    return NextResponse.json(
      { error: "Webhook secret is not configured." },
      { status: 503 }
    )
  }

  const signature = request.headers.get("stripe-signature")

  if (!signature) {
    return NextResponse.json({ error: "No signature." }, { status: 400 })
  }

  // The raw body, byte for byte — parsing it first would break the signature.
  const payload = await request.text()

  let event: Stripe.Event

  try {
    // The async variant verifies with Web Crypto, which is what this runtime
    // actually has.
    event = await getStripe().webhooks.constructEventAsync(
      payload,
      signature,
      secret
    )
  } catch (error) {
    // An unverified payload is someone else's guess at our billing state, so it
    // never reaches the database.
    console.error("[stripe] signature verification failed", error)

    return NextResponse.json({ error: "Invalid signature." }, { status: 400 })
  }

  if (!HANDLED_EVENTS.has(event.type)) {
    // 200, deliberately: an unhandled event is not a failure, and a 4xx here
    // would have Stripe retry it for days.
    return NextResponse.json({ received: true, handled: false })
  }

  try {
    switch (event.type) {
      case "checkout.session.completed":
      case "checkout.session.async_payment_succeeded":
      case "checkout.session.async_payment_failed": {
        const session = event.data.object

        // The one gate that matters on this event: `complete` is not `paid`.
        if (session.payment_status === "unpaid") break

        const subscriptionId = subscriptionIdFrom(session.subscription)

        // A one-off payment would have no subscription; ours always do.
        if (subscriptionId) await syncSubscriptionById(subscriptionId)

        break
      }

      case "customer.subscription.created":
      case "customer.subscription.updated":
      case "customer.subscription.deleted": {
        // Re-read rather than trusting the event body: it arrives without the
        // expansions the card columns need, and events can land out of order,
        // so the fresh copy is the one that's true.
        await syncSubscriptionById(event.data.object.id)

        break
      }

      case "invoice.paid":
      case "invoice.payment_failed": {
        // Since Basil the subscription hangs off `parent`, not the invoice
        // itself — an invoice can equally have been generated by a quote.
        const subscriptionId = subscriptionIdFrom(
          event.data.object.parent?.subscription_details?.subscription
        )

        if (subscriptionId) await syncSubscriptionById(subscriptionId)

        break
      }
    }
  } catch (error) {
    console.error(`[stripe] handling ${event.type} failed`, error)

    // 500 so Stripe retries with backoff. Every handler above re-reads state
    // from Stripe and upserts, so replaying one is harmless.
    return NextResponse.json({ error: "Handler failed." }, { status: 500 })
  }

  return NextResponse.json({ received: true, handled: true })
}
